- hosts: localhost

  vars:
    source_ssh_key: "./.ssh/id_rsa"
    dest_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    source_gpg_private_key: "./.gpg_keys/private.key"
    source_gpg_public_key: "./.gpg_keys/public.key"
  pre_tasks:
    - name: Update Brew
      community.general.homebrew:
        update_homebrew: yes
      tags:
        - install
        - core
  tasks:
    - include: ansible/tasks/ssh.yaml
    - include: ansible/tasks/gpg.yaml
    - include: ansible/tasks/git-setup.yaml
    - include: ansible/tasks/cli-tools.yaml
    - include: ansible/tasks/gui-tools.yaml
    - include: ansible/tasks/zsh.yaml
    - include: ansible/tasks/app-store-apps.yaml
    # dock is disabled until this issue is fixed: https://github.com/kcrawford/dockutil/issues/127
    # - include: ansible/tasks/dock.yaml
    - include: ansible/tasks/fonts.yaml
    - include: ansible/tasks/themes.yaml
    - include: ansible/tasks/osx.yaml
    - include: ansible/tasks/iterm.yaml
    - include: ansible/tasks/nvim.yaml
    - include: ansible/tasks/node.yaml
    - include: ansible/tasks/dotfiles.yaml
