- hosts: localhost

  pre_tasks:
    - name: Update Brew
      community.general.homebrew:
        update_homebrew: yes
        upgrade_all: yes
      tags:
        - install
        - core
  tasks:
    - include: ansible/tasks/git-setup.yaml
    - include: ansible/tasks/cli-tools.yaml
    - include: ansible/tasks/gui-tools.yaml
    - include: ansible/tasks/zsh.yaml
    - include: ansible/tasks/app-store-apps.yaml
    - include: ansible/tasks/dock.yaml
    # - include: tasks/ssh.yml
    # - include: tasks/core-setup.yml
    # - include: tasks/node-setup.yml
    # - include: tasks/npm-packages.yml
    # - include: tasks/zsh-setup.yml
    # - include: tasks/slack-setup.yml
    # - include: tasks/personal-projects.yml
    # - include: tasks/nvim-setup.yml
    # - include: tasks/brave.yml
    # - include: tasks/dotfiles.yml
    # - include: tasks/productivity-tools.yml
