- hosts: localhost
  roles:
    - { role: elliotweiser.osx-command-line-tools }
  vars_files:
    - ./defaults.yaml
  pre_tasks:
    - name: Update Brew
      community.general.homebrew:
        update_homebrew: yes
      tags:
        - install
        - core
  tasks:
    - import_tasks: ansible/tasks/git-setup.yaml
    - import_tasks: ansible/tasks/app-store-apps.yaml
    - import_tasks: ansible/tasks/cli-tools.yaml
    - import_tasks: ansible/tasks/gui-tools.yaml
    - import_tasks: ansible/tasks/zsh.yaml
    - import_tasks: ansible/tasks/dock.yaml
    - import_tasks: ansible/tasks/fonts.yaml
    - import_tasks: ansible/tasks/themes.yaml
    - import_tasks: ansible/tasks/osx.yaml
    - import_tasks: ansible/tasks/iterm.yaml
    - import_tasks: ansible/tasks/nvim.yaml
    - import_tasks: ansible/tasks/security.yaml
    - import_tasks: ansible/tasks/dotfiles.yaml
    - import_tasks: ansible/tasks/node.yaml
    - import_tasks: ansible/tasks/rust.yaml
