- hosts: localhost
  roles:
    - { role: elliotweiser.osx-command-line-tools }
  vars:
    source_gpg_private_key: "./.gpg_keys/private.key"
    source_gpg_public_key: "./.gpg_keys/public.key"
  pre_tasks:
    - name: Update Brew
      community.general.homebrew:
        update_homebrew: yes
      tags:
        - install
        - core
  tasks:
    - include: ansible/tasks/git-setup.yaml
    - include: ansible/tasks/app-store-apps.yaml
    - include: ansible/tasks/cli-tools.yaml
    - include: ansible/tasks/gui-tools.yaml
    - include: ansible/tasks/zsh.yaml
    - include: ansible/tasks/dock.yaml
    - include: ansible/tasks/fonts.yaml
    - include: ansible/tasks/themes.yaml
    - include: ansible/tasks/osx.yaml
    - include: ansible/tasks/iterm.yaml
    - include: ansible/tasks/nvim.yaml
    - include: ansible/tasks/security.yaml
    - include: ansible/tasks/dotfiles.yaml
    - include: ansible/tasks/node.yaml
