- hosts: localhost

  vars:
    source_gpg_private_key: "./.gpg_keys/private.key"
    source_gpg_public_key: "./.gpg_keys/public.key"
    source_ssh_key: "./.ssh/id_rsa"
    dest_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - name: Ensure .ssh and .gnupg directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0700'
      loop:
        - "{{ lookup('env', 'HOME') }}/.ssh"
        - "{{ lookup('env', 'HOME') }}/.gnupg"
      ignore_errors: no

    - import_tasks: ansible/tasks/gpg.yaml
    - import_tasks: ansible/tasks/ssh.yaml

    - name: Set correct permissions for SSH key
      file:
        path: "{{ dest_ssh_key }}"
        mode: '0600'
      when: dest_ssh_key is file
      ignore_errors: no

    - name: Verify key installations
      block:
        - name: Check GPG key
          command: gpg --list-secret-keys
          register: gpg_check
          changed_when: false
          failed_when: gpg_check.rc != 0

        - name: Check SSH key
          stat:
            path: "{{ dest_ssh_key }}"
          register: ssh_check

      rescue:
        - name: Key installation failed
          fail:
            msg: "Failed to install keys. Please check the error messages above."
