- hosts: localhost

  vars:
    source_ssh_key: "./.ssh/id_rsa"
    dest_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - import_tasks: ansible/tasks/gpg.yaml
    - import_tasks: ansible/tasks/ssh.yaml
