- name: Install apps from App Store
  tags:
    - app-store
    - install
  vars:
    apps:
      - id: 441258766
        name: Magnet
      - id: 411643860
        name: DaisyDisk
      - id: 1091189122
        name: Bear
      - id: 1532419400
        name: MeetingBar
      - id: 457622435
        name: Yoink
      - id: 803453959
        name: Slack
      - id: 1875466942
        name: Perplexity
  community.general.mas:
    id: "{{ item.id }}"
    state: latest
  loop: "{{ apps }}"
  loop_control:
    loop_var: item
    label: "{{ item.name }}"
  ignore_errors: true
