- name: Install Magnet
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 441258766
    state: latest

- name: Install DaisyDisk
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 411643860
    state: latest

- name: Install Bear
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1091189122
    state: latest

- name: Install MeetingBar
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 1532419400
    state: latest

- name: Install Xcode
  ignore_errors: yes
  tags:
    - app-store
  community.general.mas:
    id: 497799835
    state: latest
