- name: Install useful cli packages
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - tmux
    - fzf
    - ripgrep
    - z
    - gh
    - shellcheck
    - wget
    - yarn
    - watchman
    - tree
    - curl
    - htop
    - thefuck
    - mas
    - starship
    - ansible-lint
    - httpie
    - jq
    - ranger
    - spotify-tui
    - lazygit
    - glances
    - tldr
    - lazydocker
    - fd
    - asciinema
  tags:
    - install
    - productivity
    - cli

- name: Better fzf shell integration
  ansible.builtin.shell: $(brew --prefix)/opt/fzf/install
  tags:
    - install
    - productivity
    - cli

- name: Check if github dashboard cli tool is installed already
  ansible.builtin.shell: gh extension list | grep gh-dash
  register: github_dash
  ignore_errors: true
  tags:
    - install
    - productivity
    - cli

- name: Github dashboard extension
  ansible.builtin.shell: gh extension install dlvhdr/gh-dash
  when: github_dash is failed
  tags:
    - install
    - productivity
    - cli
