- name: Install useful cli packages
  community.general.homebrew:
    name:
      [
        "tmux",
        "fzf",
        "ripgrep",
        "z",
        "gh",
        "shellcheck",
        "wget",
        "yarn",
        "watchman",
        "tree",
        "curl",
        "htop",
        "thefuck",
        "mas",
      ]
  tags:
    - install
    - productivity
    - cli

- name: Better fzf shell integration
  ansible.builtin.shell: $(brew --prefix)/opt/fzf/install
  tags:
    - install
    - productivity
    - cli
