- name: Configure dock
  block:
    - name: Install dockutil
      community.general.homebrew:
        name: dockutil
        state: latest
        greedy: yes
        install_options: force
      ignore_errors: true
      tags:
        - install
        - dock

    - name: Clear dock
      shell: dockutil --remove all --no-restart
      tags:
        - install
        - dock

    - name: Setup dock
      shell: dockutil --add {{ item }} --no-restart
      with_items:
        - /Applications/Slack.app
        - /Applications/Spotify.app
        - /Applications/Fantastical.app
        - "'' --type small-spacer --section apps --after Obsidian"
        - /Applications/Raycast.app
        - /Applications/Alacritty.app
        - /Applications/Visual\ Studio\ Code.app
        - /Applications/Visual\ Studio\ Code\ -\ Insiders.app
        - /Applications/Zed.app
        - /Applications/Orbstack.app
        - "'' --type small-spacer --section apps --after VSCode"
        - /Applications/Arc.app
        - /Applications/Google\ Chrome.app
        - /Applications/Firefox.app
        - "'' --type small-spacer --section apps --after Firefox"
        - /Applications/Bruno.app
        - /Applications/TablePlus.app
        - /Applications/Sourcetree.app
      ignore_errors: yes
      tags:
        - install
        - dock
        - work

    - name: Add dock items specific to personal machine
      shell: dockutil --add {{ item }} --no-restart
      with_items:
        - "'' --type small-spacer --section apps --after Sourcetree"
        - /Applications/ChatGPT.app
        - /Applications/Obsidian.app
      ignore_errors: yes
      tags:
        - install
        - dock
        - personal

    - name: Restart dock
      shell: "/usr/bin/killall Dock"
      tags:
        - install
        - dock
