- name: Install latest Git
  community.general.homebrew:
    name: git
    state: latest
  tags:
    - git-personal

- name: Create global .gitignore
  ansible.builtin.template:
    src: ../templates/.global_gitignore
    dest: ~/.global_gitignore
    mode: "0644"
  tags:
    - git-personal

- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "paul.hammond@gmail.com"
  tags:
    - git-personal

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Paul Hammond"
  tags:
    - git-personal

- name: Git set pull to rebase
  git_config:
    name: pull.rebase
    scope: global
    value: "true"
  tags:
    - git-personal

- name: Set nvim as default git editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: nvim
  tags:
    - git-personal

- name: Set global git ignore
  community.general.git_config:
    name: core.excludesfile
    scope: global
    value: ~/.global_gitignore
  tags:
    - git-personal

- name: Set git fetch to always prune
  community.general.git_config:
    name: fetch.prune
    scope: global
    value: "true"
  tags:
    - git-personal

- name: Set global git default branch name
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main
  tags:
    - git-personal

- name: Set global git gpg key
  community.general.git_config:
    name: user.signingkey
    scope: global
    value: 5016355A88C64BE0
  tags:
    - git-personal

- name: Set global git always gpgsign
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: "true"
  tags:
    - git-personal
