- name: Install latest Git
  community.general.homebrew:
    name: git
    state: latest

- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "paul.hammond@gmail.com"
  tags:
    - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Paul Hammond"
  tags:
    - git-personal
- name: Git set pull to rebase
  git_config:
    name: pull.rebase
    scope: global
    value: "true"
  tags:
    - git-personal
- name: Add a setting to ~/.gitconfig
  community.general.git_config:
    name: core.editor
    scope: global
    value: vim
  tags:
    - git-personal
