- name: Tapping homebrew/cask-versions to get alternate versions
  homebrew_tap:
    name: homebrew/cask-versions
  tags:
    - install
    - gui
    - productivity

- name: Install Gui tools via brew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
    greedy: yes
  ignore_errors: true
  with_items: "{{ gui_packages }}"
  tags:
    - install
    - gui
    - productivity

- name: Install alternative Gui tools via brew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
    greedy: yes
  ignore_errors: true
  with_items: "{{ alternate_gui_versions }}"
  tags:
    - install
    - gui
    - productivity

# See below for an explanation of the --no-quarantine option for alacritty
# https://github.com/alacritty/alacritty/issues/4673#issuecomment-771291615

- name: Install alacritty with '--no-quarantine' option
  community.general.homebrew_cask:
    name: alacritty
    state: latest
    greedy: yes
    install_options: "no-quarantine"
  tags:
    - install
    - gui
    - productivity
