- name: Install neovim
  community.general.homebrew:
    name: neovim
    state: latest
  tags:
    - install
    - productivity
    - cli
    - nvim

- name: Setup NvChad Neovim Configuration
  git:
    repo: "https://github.com/NvChad/NvChad"
    dest: "~/.config/nvim"
    depth: 1
  tags:
    - install
    - productivity
    - cli
    - nvim
