- name: Show status bar in finder
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
    state: present
  tags:
    - install
    - osx

- name: Show path bar in finder
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathBar
    type: bool
    value: true
    state: present
  tags:
    - install
    - osx

- name: Show hidden files in finder
  osx_defaults:
    domain: com.apple.Finder
    key: AppleShowAllFiles
    type: bool
    value: true
    state: present
  tags:
    - install
    - osx

# - name: map Esc(ape) to Caps Lock
#   command: hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x700000029}]}'
- name: Set automatic software updates to true
  osx_defaults:
    domain: /Library/Preferences/com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: int
    value: 1
  become: yes
  tags:
    - install
    - osx

- name: Restart finder
  changed_when: true
  command: killall Finder
  tags:
    - install
    - osx
