- name: Check if Rust is installed
  ansible.builtin.shell: rustc --version >/dev/null 2>&1
  register: rust_installed
  ignore_errors: true
  tags:
    - install
    - productivity
    - rust

- name: Install Rust
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  tags:
    - install
    - productivity
    - rust
  when: not rust_installed.rc == 0
  register: rust_install_output
  changed_when: "'Rust appears to be installed now' in rust_install_output.stdout"
  notify: print_rust_install_output

- name: Print Rust already installed message
  debug:
    msg: "Rust is already installed."
  when: not rust_install_output.changed
  tags:
    - install
    - productivity
    - rust
