- name: Check if Rust is installed
  command: "rustc --version"
  register: rust_installed
  ignore_errors: true
  tags:
    - install
    - productivity
    - rust

- name: Install Rust
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  tags:
    - install
    - productivity
    - rust
  when: not rust_installed.rc == 0
