- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_ssh_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - personal-ssh
- name: Install ssh key
  copy:
    src: "{{ source_ssh_key }}"
    dest: "{{ dest_ssh_key }}"
    mode: 0600
  tags:
    - personal-ssh
- name: Install ssh key public
  copy:
    src: "{{ source_ssh_key }}.pub"
    dest: "{{ dest_ssh_key }}.pub"
    mode: 0644
  tags:
    - personal-ssh
- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', '.ssh/id_rsa.pub')}}"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
