- name: Cloning Dracula iterm theme
  ansible.builtin.git:
    repo: "https://github.com/dracula/iterm.git"
    dest: ~/dracula.iterm-theme
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - themes
    - zsh

- name: Cloning Catppuccin alacritty theme
  ansible.builtin.git:
    repo: "https://github.com/catppuccin/alacritty.git"
    dest: ~/.config/alacritty/catppuccin
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - themes
    - zsh

- name: Cloning Alacritty themes
  ansible.builtin.git:
    repo: "https://github.com/alacritty/alacritty-theme.git"
    dest: ~/.config/alacritty/themes
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - themes
    - zsh
