- name: Tap FelixKratz formulae
  community.general.homebrew_tap:
    name: FelixKratz/formulae
  tags:
    - install
    - gui
    - window-management

- name: Install window management (aerospace and borders)
  community.general.homebrew:
    name:
      - "nikitabobko/tap/aerospace"
      - "borders"
    state: latest
  ignore_errors: yes
  tags:
    - install
    - gui
    - window-management
