- name: Install zsh
  community.general.homebrew:
    name: ["zsh"]
  tags:
    - install
    - zsh
    - productivity

- name: Change shell to zsh
  become: true
  become_method: sudo
  shell: chsh -s $(which zsh) {{ ansible_user_id }}
  changed_when: true
  tags:
    - install
    - zsh
    - productivity

- name: Check to see if oh-my-zsh is already installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh
  tags:
    - install
    - zsh
    - productivity

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - install
    - zsh
    - productivity
  when: not oh_my_zsh.stat.exists

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
    version: master
  tags:
    - install
    - zsh
    - productivity
