- name: Install zsh
  community.general.homebrew:
    name: ["zsh"]
  tags:
    - install
    - zsh
    - dotfiles
    - productivity

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - install
    - zsh
    - dotfiles
    - productivity
  become: true

- name: Check to see if oh-my-zsh is already installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh
  tags:
    - install
    - zsh
    - dotfiles
    - productivity

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - install
    - zsh
    - dotfiles
    - productivity
  when: oh_my_zsh.stat.exists == False

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - install
    - zsh
    - dotfiles
    - productivity
